version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    depends_on:
      - backend
